-- MySQL Script generated by MySQL Workbench
-- Thu Feb 12 13:42:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema point_payment_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema point_payment_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `point_payment_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `point_payment_db` ;

-- -----------------------------------------------------
-- Table `point_payment_db`.`member_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_payment_db`.`member_types` (
  `member_type_id` INT NOT NULL AUTO_INCREMENT,
  `member_type_code` VARCHAR(10) NOT NULL,
  `member_type_name` VARCHAR(10) NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`member_type_id`),
  UNIQUE INDEX `member_type_id_UNIQUE` (`member_type_id` ASC) VISIBLE,
  UNIQUE INDEX `member_type_code_UNIQUE` (`member_type_code` ASC) VISIBLE,
  UNIQUE INDEX `member_type_name_UNIQUE` (`member_type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_payment_db`.`operation_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_payment_db`.`operation_types` (
  `operation_type_id` INT NOT NULL AUTO_INCREMENT,
  `operation_type_name` VARCHAR(10) NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`operation_type_id`),
  UNIQUE INDEX `operation_type_id_UNIQUE` (`operation_type_id` ASC) VISIBLE,
  UNIQUE INDEX `operation_type_name_UNIQUE` (`operation_type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_payment_db`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_payment_db`.`logs` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `operation_type_id` INT NOT NULL,
  `target_member_id` INT NOT NULL,
  `class_item_id` INT NOT NULL,
  `charge` INT NULL,
  `used` INT NULL,
  `remaining` INT NOT NULL,
  `members_stuff_member_id` INT NOT NULL,
  `members_target_member_id` INT NOT NULL,
  `operation_types_operation_type_id` INT NOT NULL,
  PRIMARY KEY (`log_id`, `members_stuff_member_id`, `members_target_member_id`),
  UNIQUE INDEX `log_id_UNIQUE` (`log_id` ASC) VISIBLE,
  INDEX `fk_logs_members1_idx` (`members_stuff_member_id` ASC) VISIBLE,
  INDEX `fk_logs_members2_idx` (`members_target_member_id` ASC) VISIBLE,
  INDEX `fk_logs_operation_types1_idx` (`operation_types_operation_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_logs_members1`
    FOREIGN KEY (`members_stuff_member_id`)
    REFERENCES `point_payment_db`.`members` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logs_members2`
    FOREIGN KEY (`members_target_member_id`)
    REFERENCES `point_payment_db`.`members` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logs_operation_types1`
    FOREIGN KEY (`operation_types_operation_type_id`)
    REFERENCES `point_payment_db`.`operation_types` (`operation_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_payment_db`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_payment_db`.`members` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `member_code` VARCHAR(10) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `hashed_pass` VARCHAR(60) NOT NULL,
  `created` DATETIME NOT NULL,
  `withdrawal` DATETIME NULL,
  `member_types_member_type_id` INT NOT NULL,
  `logs_last_stuff_log_id` INT NULL,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `member_id_UNIQUE` (`member_id` ASC) VISIBLE,
  UNIQUE INDEX `member_code_UNIQUE` (`member_code` ASC) VISIBLE,
  INDEX `fk_members_member_types_idx` (`member_types_member_type_id` ASC) VISIBLE,
  INDEX `fk_members_logs1_idx` (`logs_last_stuff_log_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_member_types`
    FOREIGN KEY (`member_types_member_type_id`)
    REFERENCES `point_payment_db`.`member_types` (`member_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_logs1`
    FOREIGN KEY (`logs_last_stuff_log_id`)
    REFERENCES `point_payment_db`.`logs` (`log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_payment_db`.`class_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_payment_db`.`class_items` (
  `class_item_id` INT NOT NULL AUTO_INCREMENT,
  `class_code` VARCHAR(10) NOT NULL,
  `class_name` VARCHAR(50) NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`class_item_id`),
  UNIQUE INDEX `class_item_id_UNIQUE` (`class_item_id` ASC) VISIBLE,
  UNIQUE INDEX `class_code_UNIQUE` (`class_code` ASC) VISIBLE,
  UNIQUE INDEX `class_name_UNIQUE` (`class_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_payment_db`.`member_class_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_payment_db`.`member_class_item` (
  `members_member_id` INT NOT NULL,
  `class_items_class_item_id` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`members_member_id`, `class_items_class_item_id`),
  INDEX `fk_member_class_item_members1_idx` (`members_member_id` ASC) VISIBLE,
  INDEX `fk_member_class_item_class_items1_idx` (`class_items_class_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_class_item_members1`
    FOREIGN KEY (`members_member_id`)
    REFERENCES `point_payment_db`.`members` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_class_item_class_items1`
    FOREIGN KEY (`class_items_class_item_id`)
    REFERENCES `point_payment_db`.`class_items` (`class_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_payment_db`.`class_fees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_payment_db`.`class_fees` (
  `member_types_member_type_id` INT NOT NULL,
  `class_items_class_item_id` INT NOT NULL,
  `class_fee` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`member_types_member_type_id`, `class_items_class_item_id`),
  INDEX `fk_class_fees_member_types1_idx` (`member_types_member_type_id` ASC) VISIBLE,
  INDEX `fk_class_fees_class_items1_idx` (`class_items_class_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_fees_member_types1`
    FOREIGN KEY (`member_types_member_type_id`)
    REFERENCES `point_payment_db`.`member_types` (`member_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_fees_class_items1`
    FOREIGN KEY (`class_items_class_item_id`)
    REFERENCES `point_payment_db`.`class_items` (`class_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
